### ISSUE TITLE
Pedagogy - General

### ISSUE THREAD

**Issue by e-dub** [mbarzegary/educational-bayesian#17]
If this is for a crash course, should the title of the iPython file say something in this regard?

Should learning goals be included?

Should a summary be included restating the most important topics learned?

Maybe consider having further into subsections to breakup the long sections.

Better introduction of the nomenclature used?

**Comment by mbarzegary** [comment]
Most of the concerns have been already addressed in previous issues. A dedicated section for the learning objective was added to the text. The title was fixed. There is no nomenclature because the focus of the work is not on the mathematics of optimization, and also there is only one equation in the whole text, which is literally just an example. A summary was added to briefly recap the learned concepts. Also regarding the sections, 6-7 more subsections were added to the module to break long sections and make them clearer.
