### ISSUE TITLE
Authorship and commits

### ISSUE THREAD

**Issue by e-dub** [mbarzegary/educational-bayesian#2]
Only three commits for the development. Was there an "offline" development that included other authors? What was the contribution of the second author?

**Comment by mbarzegary** [comment]
Yes, the development was done offline without being enclosed by a git repository, and as a result, the history of development is not available, unfortunately. From now on, we will do all the development in the repository, as we did it for addressing the issues.
This work is part of my PhD work, and the second author is my supervisor. She didn’t directly contribute to the module development, but as the general rule of scientific publications implies (and also because she had provided support on writing the paper), I included her name in the paper.
